### PR TITLE
Link to a dedicated PCB with a Pi Zero

### PR DESCRIPTION
**Pull request by Raphael-Boichot**
Hello Toxa.

I was in making PCBs these days and I found in my old files a project of dedicated PCB for the pico-GB-printer that I never finished. So I've just updated it. I've crossed checked pinout with one of my working prototype. This must avoid the hassle of finding which is SIN and SOUT.

Raphaël

### CODE REVIEW

**Comment by untoxa** [comment]
well, here? https://github.com/untoxa/pico-gb-printer/blob/main/include/globals.h#L8 :)

**Comment by untoxa** [comment]
thank you Rapahel, please note that in the readme and i merge your pull request. thank you!

**Comment by Raphael-Boichot** [comment]
I think I can also route LED to GPIO 25 if this is your default setup. This will allow user to just drop the uf2 instead of recompile the code

**Comment by Raphael-Boichot** [comment]
Ah and there is the tear button also...

**Pull request merged**
